export const fr = {
  'company.name': 'WebLeafAI',

  'nav.home': 'Accueil',
  'nav.services': 'Services',
  'nav.contact': 'Contact',
  'nav.pricing': 'Tarifs',
  
  'hero.title': 'Solutions digitales complètes',
  'hero.subtitle': 'de A à Z',
  'hero.description': 'Nous construisons et gérons votre site web de manière entièrement autonome. Nous créons des sites web sécurisés et professionnels, alimentés par une automatisation intelligente, pour donner à votre entreprise la crédibilité, la performance et le soutien dont elle a besoin pour prospérer en ligne.',
  'hero.cta': 'Commencer',
  'hero.learn': 'En savoir plus',

  'home.view_all_services': 'Voir tous les services',
  
  'services.title': 'Nos services',
  'services.subtitle': 'Tout ce dont vous avez besoin pour réussir en ligne',
  'services.websites.title': 'Solutions web complètes',
  'services.websites.description': 'Sites web professionnels créés sur mesure avec maintenance continue, hébergement et optimisation inclus.',
  'services.ai.title': 'Automatisations IA intelligentes',
  'services.ai.description': 'Chatbots intelligents, flux de travail automatisés et outils alimentés par l\'IA pour optimiser vos opérations.',
  'services.support.title': 'Support et maintenance',
  'services.support.description': 'Surveillance continue, mises à jour et support technique pour maintenir votre présence digitale.',
  'services.cta.title': 'Prêt à transformer votre entreprise ?',
  'services.cta.subtitle': 'Discutons de la manière dont nos services peuvent vous aider à atteindre vos objectifs',
  'services.cta.button': 'Démarrer votre projet',
  'services.additional.title': 'Pourquoi choisir nos services ?',
  'services.additional.fast.title': 'Ultra rapide',
  'services.additional.fast.description': 'Optimisé pour la vitesse et la performance sur tous les appareils et plateformes.',
  'services.additional.secure.title': 'Sécurisé et fiable',
  'services.additional.secure.description': 'Sécurité de niveau entreprise avec sauvegardes et surveillance régulières.',
  'services.additional.turnaround.title': 'Livraison rapide',
  'services.additional.turnaround.description': 'Livraison rapide des projets sans compromettre la qualité ou l\'attention aux détails.',
  'services.process.title': 'Notre processus',
  'services.process.subtitle': 'Approche simple, transparente et efficace pour le succès numérique',
  'services.process.step1.title': 'Consultation',
  'services.process.step1.description': 'Nous discutons de vos besoins et objectifs',
  'services.process.step2.title': 'Planification',
  'services.process.step2.description': 'Création d\'une stratégie et d\'un calendrier sur mesure',
  'services.process.step3.title': 'Développement',
  'services.process.step3.description': 'Construction de votre solution numérique',
  'services.process.step4.title': 'Lancement et support',
  'services.process.step4.description': 'Mise en ligne avec maintenance continue',
  'services.websites.features.1': 'Conception et développement sur mesure',
  'services.websites.features.2': 'Design adaptatif mobile',
  'services.websites.features.3': 'Optimisation SEO',
  'services.websites.features.4': 'Système de gestion de contenu',
  'services.websites.features.5': 'Intégration e-commerce',
  'services.websites.features.6': 'Optimisation des performances',
  'services.ai.features.1': 'Chatbots intelligents',
  'services.ai.features.2': 'Automatisation de génération de prospects',
  'services.ai.features.3': 'Intégration de systèmes de réservation',
  'services.ai.features.4': 'Flux de marketing par courriel',
  'services.ai.features.5': 'Automatisation du support client',
  'services.ai.features.6': 'Optimisation des flux de travail',
  'services.ai.features.7': 'Résumé des demandes ou documents entrants',
  'services.ai.features.8': 'Attribution automatique des demandes en fonction de la disponibilité/région',
  'services.ai.features.9': 'Et bien plus encore !',
  'services.support.features.1': 'Surveillance continue',
  'services.support.features.2': 'Mises à jour régulières',
  'services.support.features.3': 'Maintenance de la sécurité',
  'services.support.features.4': 'Optimisation des performances',
  'services.support.features.5': 'Support technique',
  'services.support.features.6': 'Sauvegarde et récupération',
  
  'pricing.meta.title': 'Tarifs et plans de maintenance web',
  'pricing.meta.description': 'Tarification transparente pour nos forfaits de maintenance web. Choisissez parmi les plans Essentiel, Croissance ou Élite avec maintenance mensuelle sans tracas.',
  'pricing.title': 'Tarifs et plans de maintenance web',
  'pricing.subtitle': 'Choisissez le forfait mensuel parfait pour une maintenance de site web sans tracas et un support complet.',
  'pricing.popular': 'Le plus populaire',
  'pricing.cta': 'Choisir le plan',
  'pricing.plans.period': '/mois',
  'pricing.plans.essential.name': 'Essentiel',
  'pricing.plans.essential.price': '49$ ',
  'pricing.plans.essential.changes': '3 modifications incluses',
  'pricing.plans.essential.description': 'Parfait pour les petites entreprises avec des besoins de maintenance de base.',
  'pricing.plans.essential.features.1': 'Jusqu\'à 3 modifications de contenu par mois (Les modifications peuvent prendre jusqu\'à 72 heures après votre demande)',
  'pricing.plans.essential.features.2': 'Hébergement web et gestion de domaine',
  'pricing.plans.essential.features.3': 'Mises à jour de sécurité et surveillance',
  'pricing.plans.essential.features.4': 'Support technique de base',
  'pricing.plans.growth.name': 'Croissance',
  'pricing.plans.growth.price': '99$ ',
  'pricing.plans.growth.changes': '10 modifications incluses',
  'pricing.plans.growth.description': 'Idéal pour les entreprises en croissance avec des mises à jour de contenu régulières.',
  'pricing.plans.growth.features.1': 'Jusqu\'à 10 modifications de contenu par mois (Les modifications peuvent prendre jusqu\'à 48 heures après votre demande)',
  'pricing.plans.growth.features.2': 'Support technique prioritaire',
  'pricing.plans.growth.features.3': 'Optimisation et surveillance SEO',
  'pricing.plans.growth.features.4': 'Fonctionnalités de sécurité avancées',
  'pricing.plans.growth.features.5': 'Optimisation des performances',
  'pricing.plans.elite.name': 'Élite',
  'pricing.plans.elite.price': '199$ ',
  'pricing.plans.elite.changes': '25 modifications + 1 demande urgente',
  'pricing.plans.elite.description': 'Solution complète pour les entreprises nécessitant des mises à jour fréquentes.',
  'pricing.plans.elite.features.1': 'Jusqu\'à 25 modifications de contenu par mois (Les modifications peuvent prendre jusqu\'à 36 heures après votre demande)',
  'pricing.plans.elite.features.2': '1 demande urgente gratuite le jour même',
  'pricing.plans.elite.features.3': 'Gestionnaire de compte dédié',
  'pricing.plans.elite.features.4': 'Outils SEO et marketing avancés',
  'pricing.plans.elite.features.5': 'Support d\'intégrations personnalisées',
  'pricing.plans.elite.features.6': 'Support téléphonique prioritaire',
  'pricing.changes.title': 'Qu\'est-ce qui compte comme une modification ?',
  'pricing.changes.subtitle': 'Répartition claire de ce qui est inclus dans votre allocation mensuelle de modifications.',
  'pricing.changes.text.title': 'Modifications de texte',
  'pricing.changes.text.description': 'Mises à jour de contenu, changements de texte et modifications textuelles',
  'pricing.changes.images.title': 'Échange d\'images',
  'pricing.changes.images.description': 'Remplacements de photos et optimisations d\'images',
  'pricing.changes.contact.title': 'Mises à jour de contact',
  'pricing.changes.contact.description': 'Numéros de téléphone, adresses et informations de contact',
  'pricing.changes.blog.title': 'Articles de blog',
  'pricing.changes.blog.description': 'Nouveaux articles et ajouts de contenu de blog',
  'pricing.changes.notincluded.title': 'Non inclus :',
  'pricing.changes.notincluded.description': 'Création de nouvelles pages, refonte complète, intégrations tierces ou changements structurels majeurs nécessitent des devis séparés.',
  'pricing.addons.title': 'Services complémentaires',
  'pricing.addons.subtitle': 'Besoin de quelque chose en plus ? Nous vous couvrons avec des options complémentaires flexibles.',
  'pricing.addons.extra.title': 'Modification supplémentaire',
  'pricing.addons.extra.price': '19$ ',
  'pricing.addons.extra.description': 'Modification de contenu supplémentaire au-delà de votre limite de plan',
  'pricing.addons.urgent.title': 'Urgent le jour même',
  'pricing.addons.urgent.price': '75$ ',
  'pricing.addons.urgent.description': 'Completion prioritaire le jour même pour les demandes urgentes',
  'pricing.addons.newpage.title': 'Conception de nouvelle page',
  'pricing.addons.newpage.price': '85$-150$ ',
  'pricing.addons.newpage.description': 'Création de page personnalisée avec design professionnel',
  'pricing.policy.title': 'Notre politique',
  'pricing.policy.newbuilds.title': 'Nouveaux sites web',
  'pricing.policy.newbuilds.description': 'Pour les nouveaux projets de sites web, nous incluons des modifications de contenu raisonnables et des ajustements dans les 10 premiers jours après le lancement sans frais supplémentaires. Les pages supplémentaires au-delà de la portée originale seront facturées séparément selon notre tarification complémentaire.',
  'pricing.cta.title': 'Prêt à commencer ?',
  'pricing.cta.subtitle': 'Choisissez votre plan et laissez-nous gérer la maintenance de votre site web pendant que vous vous concentrez sur la croissance de votre entreprise.',
  'pricing.cta.button': 'Contactez-nous aujourd\'hui',
  
  'features.title': 'Pourquoi nous choisir ?',
  'features.handsoff.title': 'Totalement autonome',
  'features.handsoff.description': 'Nous nous occupons de tout pour que vous puissiez vous concentrer sur votre entreprise.',
  'features.allinone.title': 'Solution tout-en-un',
  'features.allinone.description': 'Site web, hébergement, domaine, mises à jour - tout inclus.',
  'features.ai.title': 'Automatisation IA',
  'features.ai.description': 'Outils intelligents qui travaillent en continu pour développer votre entreprise.',
  'features.support.title': 'Support expert',
  'features.support.description': 'Équipe professionnelle prête à vous aider quand vous en avez besoin.',
  
  'contact.title': 'Prêt à commencer ?',
  'contact.subtitle': 'Parlez-nous de votre projet et nous créerons une solution sur mesure pour vous.',
  'contact.form.title': 'Envoyez-nous un message',
  'contact.form.name': 'Nom complet',
  'contact.form.name.placeholder': 'John Doe',
  'contact.form.company': 'Nom de l\'entreprise',
  'contact.form.company.placeholder': 'Votre Entreprise',
  'contact.form.role': 'Votre rôle',
  'contact.form.role.placeholder': 'PDG, Directeur Marketing, etc.',
  'contact.form.phone': 'Numéro de téléphone',
  'contact.form.phone.placeholder': '(514) 123-4567',
  'contact.form.email': 'Adresse courriel',
  'contact.form.email.placeholder': 'votre@courriel.com',
  'contact.form.preference': 'Comment préférez-vous être contacté ?',
  'contact.form.preference.placeholder': 'Sélectionner la préférence de contact',
  'contact.form.preference.phone': 'Appel téléphonique',
  'contact.form.preference.email': 'Courriel',
  'contact.form.preference.either': 'L\'un ou l\'autre convient',
  'contact.form.budget': 'Votre budget',
  'contact.form.budget.placeholder': 'Votre budget',
  'contact.form.budget.option1': 'Moins de 1 500$ ',
  'contact.form.budget.option2': '1 500$ - 5 000$ ',
  'contact.form.budget.option3': '5 000$ - 10 000$ ',
  'contact.form.budget.option4': '10 000$ - 25 000$ ',
  'contact.form.budget.option5': 'Plus de 25 000$ ',
  'contact.form.services': 'Services d\'intérêt',
  'contact.form.services.placeholder': 'Sélectionner les services',
  'contact.form.services.website': 'Développement web',
  'contact.form.services.ai': 'Automatisation IA',
  'contact.form.services.both': 'Les deux services',
  'contact.form.message': 'Parlez-nous de votre projet',
  'contact.form.message.placeholder': 'Parlez-nous de votre projet, de vos objectifs et de vos exigences spécifiques...',
  'contact.form.submit': 'Envoyer le message',
  'contact.info.title': 'Contactez-nous',
  'contact.info.email': 'hello@webleafai.ca',
  'contact.info.email.title': 'Courriel',
  'contact.info.phone.title': 'Téléphone',
  'contact.info.location.title': 'Emplacement',
  'contact.info.location.text': 'Nous sommes situés à Montréal',
  'contact.info.description': 'Prêt à transformer votre présence digitale ? Nous sommes là pour vous aider à chaque étape.',
  'contact.workwithus.title': 'Pourquoi travailler avec nous ?',
  'contact.workwithus.item1': 'Consultation gratuite et évaluation de projet',
  'contact.workwithus.item2': 'Solutions sur mesure adaptées à vos besoins',
  'contact.workwithus.item3': 'Tarification transparente sans frais cachés',
  'contact.workwithus.item4': 'Support et maintenance continus inclus',
  'contact.faq.title': 'Questions fréquemment posées',
  'contact.faq.q1': 'Combien de temps faut-il pour créer un site web ?',
  'contact.faq.a1': 'Généralement 1 à 2 semaines pour un site web standard, en fonction de la complexité et des fonctionnalités requises.',
  'contact.faq.q2': 'Qu\'est-ce qui est inclus dans les frais mensuels ?',
  'contact.faq.a2': 'Hébergement, domaine, mises à jour de sécurité, mises à jour de contenu, support technique et surveillance des performances.',
  'contact.faq.q3': 'Pouvez-vous intégrer des fonctionnalités d\'IA dans des sites web existants ?',
  'contact.faq.a3': 'Oui, nous pouvons ajouter des chatbots, des automatisations et des fonctionnalités d\'IA à la plupart des sites et plateformes existants.',
  
  'footer.description': 'Solutions digitales complètes pour les entreprises modernes. Nous gérons la technologie, vous vous concentrez sur la croissance.',
  'footer.services.title': 'Services',
  'footer.services.websites': 'Développement web',
  'footer.services.ai': 'Automatisation IA',
  'footer.services.maintenance': 'Maintenance et support',
  'footer.company.title': 'Entreprise',
  'footer.company.about': 'À propos',
  'footer.company.contact': 'Contact',
  'footer.rights': 'Tous droits réservés.',

  'contact.form.error.title': 'Informations manquantes',
  'contact.form.error.description': 'Veuillez remplir tous les champs obligatoires.',
  'contact.form.success.title': 'Message envoyé !',
  'contact.form.success.description': 'Merci de votre intérêt. Nous vous répondrons bientôt !',
  'contact.form.senderror.title': 'Oups ! Quelque chose s\'est mal passé.',
  'contact.form.senderror.description': 'Un problème est survenu lors de l\'envoi de votre message. Veuillez réessayer plus tard.',
  'contact.form.sending': 'Envoi en cours...',

  'cookies.banner.text': 'Notre site ne collecte aucun cookie ni aucune donnée personnelle des visiteurs. Votre vie privée est importante pour nous.',
  'cookies.banner.button': 'Compris !'
};